openapi: 3.0.3
info:
  title: API Pacientes
  description: API para manejar pacientes en el sistema de turnos médicos
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /pacientes:
    get:
      summary: Listar todos los pacientes
      responses:
        "200":
          description: Lista de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Paciente"

    post:
      summary: Crear un paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PacienteInput"
      responses:
        "201":
          description: Paciente creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paciente"

  /pacientes/{id}:
    get:
      summary: Obtener paciente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Paciente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paciente"
        "404":
          description: Paciente no encontrado

    put:
      summary: Actualizar paciente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PacienteInput"
      responses:
        "200":
          description: Paciente actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paciente"
        "404":
          description: Paciente no encontrado

    delete:
      summary: Eliminar paciente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Paciente eliminado
        "404":
          description: Paciente no encontrado

components:
  schemas:
    Paciente:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        apellido:
          type: string
        dni:
          type: string
        email:
          type: string
        telefono:
          type: string

    PacienteInput:
      type: object
      required:
        - nombre
        - apellido
      properties:
        nombre:
          type: string
        apellido:
          type: string
        dni:
          type: string
        email:
          type: string
        telefono:
          type: string
