openapi: 3.0.3
info:
  title: API Pacientes
  description: API para manejar pacientes en el sistema de turnos médicos
  version: 1.0.2
servers:
  - url: http://localhost:3000

paths:
  /pacientes:
    get:
      summary: Listar todos los pacientes
      responses:
        "200":
          description: Lista de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Paciente"

    post:
      summary: Crear un paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PacienteInput"
      responses:
        "201":
          description: Paciente creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paciente"
        "400":
          description: Datos inválidos o campos faltantes

  /pacientes/{id}:
    get:
      summary: Obtener paciente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Paciente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paciente"
        "404":
          description: Paciente no encontrado

    put:
      summary: Actualizar paciente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PacienteInput"
      responses:
        "200":
          description: Paciente actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paciente"
        "400":
          description: Datos inválidos o campos faltantes
        "404":
          description: Paciente no encontrado

    delete:
      summary: Eliminar paciente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Paciente eliminado correctamente
        "404":
          description: Paciente no encontrado

components:
  schemas:
    Paciente:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Juan
        apellido:
          type: string
          example: Pérez
        dni:
          type: string
          example: "43235290"
        email:
          type: string
          example: juan.perez@example.com
        telefono:
          type: string
          example: "+541123456789"

    PacienteInput:
      type: object
      required:
        - dni
        - email
        - telefono
      properties:
        nombre:
          type: string
          example: Juan
          description: Opcional
        apellido:
          type: string
          example: Pérez
          description: Opcional
        dni:
          type: string
          pattern: "^[0-9]{7,8}$"
          example: "43235290"
          description: Debe contener solo números y tener entre 7 y 8 dígitos.
        email:
          type: string
          format: email
          example: juan.perez@example.com
          description: Debe tener un formato de correo electrónico válido.
        telefono:
          type: string
          pattern: "^\\+?\\d{7,15}$"
          example: "+541123456789"
          description: Puede incluir un prefijo internacional (+54) y debe tener entre 7 y 15 dígitos.
